name: solarpv-eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - scikit-learn
  - statsmodels
  - pyarrow
  - nbstripout
  - pip
  - pip:
      - xgboost
      - optuna
      - deap
      - imbalanced-learn
      - faiss-cpu
      - shap
      - lime
      - scikit-posthocs
      - arch
      - ydata-profiling
      - pytest
